### PR TITLE
A faster prettier voxblox

### PR DESCRIPTION
**Pull request by ZacharyTaylor**
Almost certainly not ready for merging, but I will probably refer to the pr when talking about some of the more questionable hacks in it.

peek 2017-08-07 23-05

Long story short this pull request makes the fast integrator 5x slower, but a hell of a lot prettier. It also threads it and the concurrency is good enough that we are only a bit slower then before.

Meshing is also over 10x faster as we were previously computing unneeded normals.
Most publishing can now be disabled as this bottlenecks high res maps.

Oh my tests we now get a reliable 5Hz on 2cm voxels with voxel carving on.

### CODE REVIEW

**Comment by ZacharyTaylor** [comment]
The branch is now in a state where it is ready for review.

New in this pull request:
- Ray traces blocks to allow preallocation of all memory needed, allowing concurrent access to the block hash map.
- Uses an array of 4096 mutexes to allow finer grained locking of voxels. This locking happens automatically when updateVoxel is called.
- Bringing together some of the common functions from the merged, fast and simple integrators to reduce code double up.
- Threading of the simple and fast integrator and changing the merging integrator to use the same threading strategy as the others.
- Removed second computation of normals in meshing, as this is done for free in the marching cubes part.
- Added flags for disabling some published information.

**Comment by helenol** [comment]
@ZacharyTaylor when you get the chance, can you merge master into this branch? (Has conflicts)
Will do the review later today.

File: voxblox/include/voxblox/utils/approx_hash_array.h [hunk 1]
```diff
@@ -0,0 +1,153 @@
...
+// only one can be store.
+
+// Basic container, given in an index and get the element that was stored there.
+// There are 2^unmasked_bits_ elements in the container, which element is
+// returned depends on your hashing function.
+// Uses at least 2^unmaksed_bits * sizeof(StoreElement) bytes of ram
+
+namespace voxblox {
+template <size_t unmasked_bits_, typename StoredElement>
+class ApproxHashArray {
```
Comment (mfehr) [inline voxblox/include/voxblox/utils/approx_hash_array.h]: How confident are you that this is all correct? Because for such fundamental containers it would be nice to have at least some basic unit testing :)

File: voxblox_ros/src/voxblox_node.cc [hunk 2]
```diff
@@ -191,15 +197,25 @@ VoxbloxNode::VoxbloxNode(const ros::NodeHandle& nh,
...
   // Advertise topics.
   mesh_pub_ =
       nh_private_.advertise<visualization_msgs::MarkerArray>("mesh", 1, true);
-  surface_pointcloud_pub_ =
-      nh_private_.advertise<pcl::PointCloud<pcl::PointXYZRGB>>(
-          "surface_pointcloud", 1, true);
-  tsdf_pointcloud_pub_ = nh_private_.advertise<pcl::PointCloud<pcl::PointXYZI>>(
-      "tsdf_pointcloud", 1, true);
+
+  if (publish_tsdf_info_) {
```
Comment (mfehr) [inline voxblox_ros/src/voxblox_node.cc]: Very nice, when I recently used voxblox I was amazed by how much stuff it publishes :)

File: voxblox/include/voxblox/integrator/tsdf_integrator.h [hunk 3]
```diff
@@ -65,6 +69,159 @@ class TsdfIntegratorBase {
...
+    const Pointcloud& points_C_;
+    const Colors& colors_;
+    const Config& config_;
+    const Point origin_;
+    std::atomic<size_t> atomic_idx_;
+  };
+
+  // Can be used to pre-allocate all the blocks needed by the integrator. This
+  // allows thread-safe lockless block map access
+  void allocateBlocks(const Transformation& T_G_C, const Pointcloud& points_C,
```
Comment (helenol) [inline voxblox/include/voxblox/integrator/tsdf_integrator.h]: As a small sidenote re: transforming, you do need points_C for the integration as well; not just points_G. While I in general agree with trying not to duplicate work/etc., I'm not 100% sure how huge of a difference at least the pre-transform will make?

File: voxblox/include/voxblox/integrator/tsdf_integrator.h [hunk 4]
```diff
@@ -17,8 +18,11 @@
...
 #include "voxblox/core/voxel.h"
 #include "voxblox/integrator/integrator_utils.h"
+#include "voxblox/utils/approx_hash_array.h"
 #include "voxblox/utils/timing.h"
 
+#include "voxblox/core/block_hash.h"
+
 namespace voxblox {
 
 class TsdfIntegratorBase {
```
Comment (ZacharyTaylor) [inline voxblox/include/voxblox/integrator/tsdf_integrator.h]: Agreed will split it up

File: voxblox/include/voxblox/integrator/tsdf_integrator.h [hunk 5]
```diff
@@ -65,6 +69,159 @@ class TsdfIntegratorBase {
...
+            Block<TsdfVoxel>::Ptr block =
+                layer_->allocateBlockPtrByIndex(block_idx + AnyIndex(x, y, z));
+            block->updated() = true;
+          }
+        }
+      }
+    }
+  }
+
+  inline TsdfVoxel* getVoxel(const VoxelIndex& global_voxel_idx,
```
Comment (helenol) [inline voxblox/include/voxblox/integrator/tsdf_integrator.h]: :+1:
Maybe "getVoxelFromGlobalVoxelIndex" as well or whatever

File: voxblox/include/voxblox/integrator/tsdf_integrator.h [hunk 6]
```diff
@@ -65,6 +69,159 @@ class TsdfIntegratorBase {
...
+          points_C_(points_C),
+          colors_(colors),
+          config_(config),
+          origin_(T_G_C.getPosition()),
+          atomic_idx_(0) {
+      DCHECK_EQ(points_C_.size(), colors_.size());
+    }
+
+    bool getNextPoint(size_t* point_idx, Point* point_G, bool* clearing) {
+      while (atomic_idx_.load() < points_C_.size()) {
```
Comment (ZacharyTaylor) [inline voxblox/include/voxblox/integrator/tsdf_integrator.h]: If the point is too close or too far away it needs to go back and try get the next point, until it hits the end or finds a valid one

File: voxblox/include/voxblox/integrator/tsdf_integrator.h [hunk 7]
```diff
@@ -65,6 +69,159 @@ class TsdfIntegratorBase {
...
+        *point_idx = getMixedIdx(atomic_idx_.fetch_add(1));
```
Comment (ZacharyTaylor) [inline voxblox/include/voxblox/integrator/tsdf_integrator.h]: true, will change

File: voxblox/include/voxblox/integrator/tsdf_integrator.h [hunk 8]
```diff
@@ -155,109 +316,93 @@ class TsdfIntegratorBase {
...
-      }
+    timing::Timer block_timer("block_allocation");
+    allocateBlocks(T_G_C, points_C, colors);
+    block_timer.Stop();
 
-      FloatingPoint truncation_distance = config_.default_truncation_distance;
+    timing::Timer integrate_timer("integrate");
 
-      const Ray unit_ray = (point_G - origin).normalized();
+    point_getter_ =
```
Comment (helenol) [inline voxblox/include/voxblox/integrator/tsdf_integrator.h]: Because it needs to know T_G_C, points, etc. on construction and is constructed new every integration request, not once per integrator object?

File: voxblox/include/voxblox/integrator/tsdf_integrator.h (hunk 3 above)
Comment (ZacharyTaylor) [inline voxblox/include/voxblox/integrator/tsdf_integrator.h]: I agree the point getter is a bit ugly here. The idea was to place the clearing ray logic inside it so it is all in one place, but I think in practice it made things uglier.

File: voxblox/include/voxblox/integrator/tsdf_integrator.h [hunk 9]
```diff
@@ -65,6 +69,159 @@ class TsdfIntegratorBase {
...
+    std::atomic<size_t> atomic_idx_;
+  };
+
+  // Can be used to pre-allocate all the blocks needed by the integrator. This
+  // allows thread-safe lockless block map access
+  void allocateBlocks(const Transformation& T_G_C, const Pointcloud& points_C,
+                      const Colors& colors) {
+    IndexSet index_set;
+
+    point_getter_ =
```
Comment (ZacharyTaylor) [inline voxblox/include/voxblox/integrator/tsdf_integrator.h]: was a member so all threads could access it and was shared because it needs parameters on creation. I will redo it as a variable passed to threads.

File: voxblox/include/voxblox/integrator/tsdf_integrator.h [hunk 10]
```diff
@@ -65,6 +69,159 @@ class TsdfIntegratorBase {
...
+    Point point_C, point_G, origin;
+    Color color;
+    bool clearing;
+    while (point_getter_->getNextPoint(&point_C, &point_G, &color, &origin,
+                                       &clearing)) {
+      // immediately check if the voxel the point is in has already been ray
+      // traced (saves time setting up ray tracer for already used points)
+      AnyIndex block_idx =
+          getGridIndexFromPoint(point_G, layer_->block_size_inv());
+      if (index_set.count(block_idx)) {
```
Comment (ZacharyTaylor) [inline voxblox/include/voxblox/integrator/tsdf_integrator.h]: I believe that this combined with the adding neighbors means that all blocks will be allocated. I need to profile to see how significant the speed gain of this is. If it is not significant I will remove it.

File: voxblox/include/voxblox/integrator/tsdf_integrator.h [hunk 11]
```diff
@@ -155,109 +316,93 @@ class TsdfIntegratorBase {
...
+
     // Pre-compute a list of unique voxels to end on.
     // Create a hashmap: VOXEL INDEX -> index in original cloud.
     BlockHashMapType<std::vector<size_t>>::type voxel_map;
     // This is a hash map (same as above) to all the indices that need to be
     // cleared.
     BlockHashMapType<std::vector<size_t>>::type clear_map;
 
-    bundleRays(T_G_C, points_C, &voxel_map, &clear_map);
+    bundleRays(&voxel_map, &clear_map);
```
Comment (helenol) [inline voxblox/include/voxblox/integrator/tsdf_integrator.h]: While I have no opinion on whether to refactor PointGetter or not, I agree with Marius on the name obfuscating its purpose. Consider changing it to something that implies it also "stores" the data...

File: voxblox/include/voxblox/integrator/tsdf_integrator.h [hunk 12]
```diff
@@ -406,23 +492,24 @@ class MergedTsdfIntegrator : public TsdfIntegratorBase {
...
-    update_voxels_timer.Stop();
   }
 
   void integrateVoxels(
       const Transformation& T_G_C, const Pointcloud& points_C,
       const Colors& colors, bool enable_anti_grazing, bool clearing_ray,
       const BlockHashMapType<std::vector<size_t>>::type& voxel_map,
       const BlockHashMapType<std::vector<size_t>>::type& clear_map,
-      std::queue<VoxelInfo>* voxel_update_queue, size_t tid) {
+      size_t tid) {
```
Comment (helenol) [inline voxblox/include/voxblox/integrator/tsdf_integrator.h]: no need for const for fundamental types in my opinion

File: voxblox/include/voxblox/integrator/tsdf_integrator.h [hunk 13]
```diff
@@ -447,127 +534,113 @@ class MergedTsdfIntegrator : public TsdfIntegratorBase {
...
 
     integrate_timer.Stop();
   }
+
+ private:
+  static constexpr FloatingPoint voxel_sub_sample_ = 4.0f;
+  static constexpr size_t max_consecutive_ray_collisions_ = 8;
+  static constexpr size_t masked_bits_ = 20;  // 8 mb of ram per tester
+  static constexpr size_t full_reset_threshold = 10000;
+  ApproxHashSet<masked_bits_, full_reset_threshold> approx_start_tester_;
```
Comment (helenol) [inline voxblox/include/voxblox/integrator/tsdf_integrator.h]: at least a comment :D

File: voxblox/include/voxblox/mesh/mesh_integrator.h [hunk 14]
```diff
@@ -183,11 +185,7 @@ class MeshIntegrator {
       VoxelIndex corner_index = index + cube_index_offsets_.col(i);
       const VoxelType& voxel = block.getVoxelByVoxelIndex(corner_index);
 
-      // Do not extract a mesh here if one of the corner is unobserved and
-      // outside the truncation region.
-      // TODO(helenol): comment above from open_chisel, but no actual checks
-      // on distance are ever made. Definitely we should skip doing checks of
-      // voxels that are too far from the surface...
+      // Do not extract a mesh here if one of the corner is unobserved.
```
Comment (helenol) [inline voxblox/include/voxblox/mesh/mesh_integrator.h]: Cheeeeeers thanks!

File: voxblox/include/voxblox/utils/approx_hash_array.h [hunk 15]
```diff
@@ -0,0 +1,153 @@
...
+// There are several advantages and some very significant disadvantages
+// Advantages-
+// - Simple and blazing fast lockless thread-safe approximate sets
+// - Can be used to provide more fine grain locking of blocks for threading then
+// simply locking the entire layer
+// Disadvantages-
+// - Highly inefficient use of memory (allocates 2^N elements)
+// - Cannot disern between two different elements with the same hash
+// - If the hash of two elements have the same first N elements of their hash,
+// only one can be store.
```
Comment (helenol) [inline voxblox/include/voxblox/utils/approx_hash_array.h]: stored

File: voxblox/include/voxblox/utils/approx_hash_array.h [hunk 16]
```diff
@@ -0,0 +1,153 @@
...
+
+// Basic container, given in an index and get the element that was stored there.
+// There are 2^unmasked_bits_ elements in the container, which element is
+// returned depends on your hashing function.
+// Uses at least 2^unmaksed_bits * sizeof(StoreElement) bytes of ram
```
Comment (helenol) [inline voxblox/include/voxblox/utils/approx_hash_array.h]: masked

File: voxblox/include/voxblox/utils/approx_hash_array.h [hunk 17]
```diff
@@ -0,0 +1,153 @@
...
+  static constexpr size_t pseudo_map_size_ = (1 << unmasked_bits_);
+  static constexpr size_t bit_mask_ = (1 << unmasked_bits_) - 1;
+
+  std::array<StoredElement, pseudo_map_size_> pseudo_map_;
+  BlockIndexHash hasher_;
+};
+
+// Acts as a fast and thread safe set, with the serious limitation of both
+// false-negatives and false positives being possible.
+// Uses at least (2^unmaksed_bits + full_reset_threshold) * sizeof(StoreElement)
```
Comment (helenol) [inline voxblox/include/voxblox/utils/approx_hash_array.h]: masked

File: voxblox_ros/src/voxblox_node.cc (hunk 2 above)
Comment (helenol) [inline voxblox_ros/src/voxblox_node.cc]: 😉

File: voxblox/include/voxblox/integrator/tsdf_integrator.h (hunk 3 above)
Comment (mfehr) [inline voxblox/include/voxblox/integrator/tsdf_integrator.h]: @helenol yes we need both points_C and _G, but I think we should not transform them twice if it can be avoided and regarding the PointGetter, I do see how it keeps the integrator functions very short and simple, but IMO they became harder to understand, especially the data flow and it introduced this redundancy regarding the transformation. But let's discuss it when @ZacharyTaylor  is back, unless someone is in a hurry to merge this?

File: voxblox/include/voxblox/integrator/tsdf_integrator.h (hunk 8 above)
Comment (mfehr) [inline voxblox/include/voxblox/integrator/tsdf_integrator.h]: @helenol  @ZacharyTaylor yes, I get the no-default-constructor thing, but there is clearly no shared ownership with anyone -> unique_ptr :)

File: voxblox/include/voxblox/integrator/tsdf_integrator.h (hunk 12 above)
Comment (mfehr) [inline voxblox/include/voxblox/integrator/tsdf_integrator.h]: the const for fundamental types might not be strictly necessary because the params are a copy anyways, so no harm is done by changing them. However having them const would raise a compilation error should you accidentally assign something to them, which helps prevent bugs. :) (see [here, second answer](https://stackoverflow.com/questions/117293/use-of-const-for-function-parameters))

Comment (alexmillane) [inline voxblox/include/voxblox/integrator/tsdf_integrator.h]: I agree, I read somewhere once something along the lines of "pass by copy arguments are just local variables declared in a special place, so declare them const as you would any other local variable".

File: voxblox/include/voxblox/integrator/tsdf_integrator.h (hunk 8 above)
Comment (helenol) [inline voxblox/include/voxblox/integrator/tsdf_integrator.h]: Ahh yes 👍

**Comment by ZacharyTaylor** [comment]
Ok, I believe I have sorted all the review comments. Its now a lot cleaner and I am quite a bit happier with its layout / performance. @mfehr 

For the block casting for memory pre-allocation I initally ran into issues. Casting every ray was quite expensive (around 100 ms on my dataset) and the fix I had of only casting from unique starting locations and then adding the neighbors of blocks, seemed to have some rare corner cases where it would miss a block.

In the end I swapped to an approach loosely inspired by how infinitam does it. Each thread will try get a voxel from the map, if that block has not been allocated it will instead create a voxel in its own local map and use this instead. Once the integration is done a single thread goes through and adds the contents of all the local maps to the real hashmap. This is slow for the first frame, but otherwise quite efficient (maybe 5-10 ms on same tests).

Other then that changes are:
- Fixed bug where verbose would make mutexes in timers deadlock
- Fixed bug that caused rays to end 1 voxel too soon
- Removed point getter and replaced with a much smaller class that just gets the index, plus an internal function to check if the point is valid.
- Split integrator into a cc file
- Added checks for nullpointers and switched existing DCHECK_NOT_NULLs to DCHECK( != nullptr)
- Threaded mesher
- Added unit tests for approx_hash_array
- Added lots more comments around where the approx_hash_array is used
- Added some benchmarks and images to readme

**Comment by ZacharyTaylor** [comment]
Also @mfehr do you have any idea why it is now not building on ubuntu in jenkins? The differences from where it built correctly are very minor and the error is coming from the tango part,

/usr/bin/ld: CMakeFiles/mesh_tango_tsdf.dir/test/mesh_tango_tsdf.cc.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line

**Comment by ZacharyTaylor** [comment]
test this please

**Comment by ZacharyTaylor** [comment]
test this please

**Comment by helenol** [comment]
FYI this PR fixes:
 - the deadlock caused when printing timings introduced in #95
 - segfaults if running multiple (multi-threaded) TSDF servers at once in the TSDF integrator

File: voxblox/src/integrator/tsdf_integrator.cc [hunk 18]
```diff
@@ -0,0 +1,567 @@
...
+  // color blending is expensive only do it close to the surface
+  if (std::abs(sdf) < config_.default_truncation_distance) {
+    tsdf_voxel->color = Color::blendTwoColors(
+        tsdf_voxel->color, tsdf_voxel->weight, color, updated_weight);
+  }
+
+  tsdf_voxel->distance =
+      (new_sdf > 0.0) ? std::min(config_.default_truncation_distance, new_sdf)
+                      : std::max(-config_.default_truncation_distance, new_sdf);
+  tsdf_voxel->weight = std::min(config_.max_weight, new_weight);
```
Comment (mfehr) [inline voxblox/src/integrator/tsdf_integrator.cc]: how about doing this capping above when you compute the new weight?

File: voxblox/src/integrator/tsdf_integrator.cc [hunk 19]
```diff
@@ -0,0 +1,567 @@
...
+  if (dist_z > kEpsilon) {
+    return 1.0f / (dist_z * dist_z);
+  }
+  return 0.0f;
+}
+
+void SimpleTsdfIntegrator::integratePointCloud(const Transformation& T_G_C,
+                                               const Pointcloud& points_C,
+                                               const Colors& colors) {
+  std::vector<VoxelMap> temp_voxel_storage(config_.integrator_threads);
```
Comment (mfehr) [inline voxblox/src/integrator/tsdf_integrator.cc]: Are you sure this temporary voxel map is worth it? Seems to me there will be a lot of allocating and freeing going on in every integration call.

File: voxblox/src/integrator/tsdf_integrator.cc [hunk 20]
```diff
@@ -0,0 +1,567 @@
...
+                                               const Pointcloud& points_C,
+                                               const Colors& colors) {
+  timing::Timer integrate_timer("integrate");
+
+  // Pre-compute a list of unique voxels to end on.
+  // Create a hashmap: VOXEL INDEX -> index in original cloud.
+  BlockHashMapType<std::vector<size_t>>::type voxel_map;
+  // This is a hash map (same as above) to all the indices that need to be
+  // cleared.
+  BlockHashMapType<std::vector<size_t>>::type clear_map;
```
Comment (mfehr) [inline voxblox/src/integrator/tsdf_integrator.cc]: I guess it does make sense to rename BlockHasMapType, because here it clearly referes to voxel indices, right?

File: voxblox/test/test_approx_hash_array.cc [hunk 21]
```diff
@@ -0,0 +1,119 @@
...
+  // generate 1000 random elements
+  std::vector<AnyIndex> rand_indexes;
+  std::mt19937 gen(1);
+  std::uniform_int_distribution<> dis(1, 1000000);
+  for (int i = 0; i < 1000; ++i) {
+    rand_indexes.push_back(AnyIndex(dis(gen), dis(gen), dis(gen)));
+  }
+
+  // test insert and clearing
+  for (size_t i = 0; i < 50; ++i) {
```
Comment (mfehr) [inline voxblox/test/test_approx_hash_array.cc]: 50u

File: voxblox/src/integrator/tsdf_integrator.cc (hunk 19 above)
Comment (ZacharyTaylor) [inline voxblox/src/integrator/tsdf_integrator.cc]: If we want to multi-thread then unless we serialize access to the map, its size cannot change while the threads are working on it. This leaves two choices pre-allocate the blocks before each update or using temporary storage for missed blocks and merging them in later. (Or using locks inside the map but this slows things down a lot).

The pre-allocation of blocks for the cow and lady dataset usually takes 50 to 100 ms per frame. With the hack I was doing of early termination I got this down to 10 to 20 ms, but it still had issues. The cost of copying these missed blocks is usually 5 to 10 ms (much more for the first frame but much less for most of the others). 

It could be improved further, but it doesn't seem to be bottle-necking things.

File: voxblox/include/voxblox/integrator/integrator_utils.h [hunk 22]
```diff
@@ -12,25 +12,121 @@
...
+  }
+
+  // returns false if ray terminates at ray_index, true otherwise
+  bool nextRayIndex(AnyIndex* ray_index) {
+    if (at_end_) {
+      return false;
+    }
+    DCHECK(ray_index != nullptr);
+    *ray_index = curr_index_;
+    at_end_ = curr_index_ == end_index_;
```
Comment (ZacharyTaylor) [inline voxblox/include/voxblox/integrator/integrator_utils.h]: yeah, it was finishing one too early by immediately returning at_end when it should return it on the next call.

File: voxblox/src/integrator/tsdf_integrator.cc [hunk 23]
```diff
@@ -0,0 +1,567 @@
...
+    return &((*temp_voxel_storage)[global_voxel_idx]);
+  } else {
+    const VoxelIndex local_voxel_idx =
+        getLocalFromGlobalVoxelIndex(global_voxel_idx, voxels_per_side_);
+
+    return &((*last_block)->getVoxelByVoxelIndex(local_voxel_idx));
+  }
+}
+
+// NOT thread safe
```
Comment (ZacharyTaylor) [inline voxblox/src/integrator/tsdf_integrator.cc]: If we have a map scope lock then we will need to keep track of how many threads are currently reading or writing to voxels so we can tell when they have all left the map and it is safe to begin operating on it. 

We would also need all these readers to check the lock before moving into the function. This style of reader-writer lock can be difficult to implement without noticeable overhead. C++17 has a std lock type for this, but in C++11 we would need to make our own.

File: voxblox/src/integrator/tsdf_integrator.cc (hunk 18 above)
Comment (ZacharyTaylor) [inline voxblox/src/integrator/tsdf_integrator.cc]: I was mimicking the behavior already present. I am not sure what is best here, will discuss.

File: voxblox/src/integrator/tsdf_integrator.cc (hunk 23 above)
Comment (mfehr) [inline voxblox/src/integrator/tsdf_integrator.cc]: Sure, if it is too much overhead, let's not do it. But just FYI we have a reader-writer lock implementation in aslam_cv2: [reader-writer-lock.h](https://github.com/ethz-asl/aslam_cv2/blob/master/aslam_cv_common/include/aslam/common/reader-writer-lock.h) and [reader-first-reader-writer-lock.h](https://github.com/ethz-asl/aslam_cv2/blob/master/aslam_cv_common/include/aslam/common/reader-first-reader-writer-lock.h)
